# Generated by Django 2.2.2 on 2019-06-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_amount', models.IntegerField()),
                ('d_type', models.IntegerField()),
                ('attack_bonus', models.IntegerField()),
                ('dmg_bonus', models.IntegerField()),
                ('advatage_bonus', models.NullBooleanField()),
                ('attack_result', models.IntegerField()),
                ('dmg_result', models.IntegerField()),
            ],
        ),
    ]
