# Generated by Django 2.2.2 on 2019-06-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice_roller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='critic_bonus',
            field=models.NullBooleanField(),
        ),
    ]
